version: '2'

volumes:
  data:
    external: true

services:
  quack:
    image: greatbit/quack
    ports:
      - "80:80"
    links:
      - mongod:mongod
    depends_on:
      - mongod
    environment:
      WAIT_HOSTS: mongod:27017
    volumes:
      - /home/bob/quack_db:/etc/quack

  mongod:
    container_name: "mongod"
    image: mongo:4.2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db:rw


